// components/modules/notificaciones.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import {
  MessageCircle,
  Send,
  Bot,
  CheckCircle2,
  Clock,
  AlertCircle,
  User,
  Sparkles,
} from "lucide-react"
import { useState } from "react"

const contacts = [
  {
    name: "Maria Gonzalez Soto",
    rut: "12.345.678-9",
    phone: "+56 9 1234 5678",
    missing: ["Carnet Identidad"],
    urgency: "critical" as const,
    lastContact: "Hace 3 dias",
    committee: "Villa Esperanza",
  },
  {
    name: "Pedro Ramirez Lagos",
    rut: "11.222.333-4",
    phone: "+56 9 8765 4321",
    missing: ["Certificado RSH"],
    urgency: "warning" as const,
    lastContact: "Hace 1 semana",
    committee: "Poblacion Aurora",
  },
  {
    name: "Ana Muhoz Vera",
    rut: "15.678.901-2",
    phone: "+56 9 5555 1234",
    missing: ["Dominio Vigente", "Cartola Ahorro"],
    urgency: "critical" as const,
    lastContact: "Nunca contactado",
    committee: "Comite Los Aromos",
  },
  {
    name: "Luisa Torres Pino",
    rut: "14.567.890-K",
    phone: "+56 9 4444 5678",
    missing: ["Dominio Vigente"],
    urgency: "warning" as const,
    lastContact: "Hace 2 dias",
    committee: "Poblacion Aurora",
  },
]

function generateMessage(contact: typeof contacts[0]) {
  const docList = contact.missing.join(" y ")
  return `Hola ${contact.name.split(" ")[0]}, para no perder su subsidio de vivienda, necesitamos que nos envie una foto de su ${docList} vigente lo antes posible. Puede responder a este mensaje con la foto o acercarse a nuestra oficina. Cualquier duda estamos para ayudarle.`
}

export function Notificaciones() {
  const [selectedContact, setSelectedContact] = useState(0)
  const [sentMessages, setSentMessages] = useState<Set<number>>(new Set())

  const handleSend = (index: number) => {
    setSentMessages((prev) => new Set(prev).add(index))
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Contacts List */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Contactos Pendientes</CardTitle>
            <CardDescription>Beneficiarios con documentos faltantes</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 p-3">
            {contacts.map((contact, i) => (
              <button
                key={contact.rut}
                onClick={() => setSelectedContact(i)}
                className={`flex w-full items-start gap-3 rounded-lg p-3 text-left transition-colors ${
                  selectedContact === i
                    ? "bg-primary/10 border border-primary/20"
                    : "hover:bg-muted/50 border border-transparent"
                }`}
              >
                <div className="relative flex size-10 shrink-0 items-center justify-center rounded-full bg-muted">
                  <User className="size-4 text-muted-foreground" />
                  <div
                    className={`absolute -top-0.5 -right-0.5 size-3 rounded-full border-2 border-card ${
                      contact.urgency === "critical" ? "bg-destructive" : "bg-warning"
                    }`}
                  />
                </div>
                <div className="flex min-w-0 flex-col gap-0.5">
                  <span className="truncate text-sm font-medium text-foreground">{contact.name}</span>
                  <span className="text-xs text-muted-foreground">{contact.committee}</span>
                  <div className="flex flex-wrap gap-1">
                    {contact.missing.map((doc) => (
                      <Badge key={doc} variant="outline" className="text-[10px] px-1.5 py-0">
                        {doc}
                      </Badge>
                    ))}
                  </div>
                  <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
                    <Clock className="size-2.5" />
                    {contact.lastContact}
                  </div>
                </div>
                {sentMessages.has(i) && (
                  <CheckCircle2 className="ml-auto size-4 shrink-0 text-success" />
                )}
              </button>
            ))}
          </CardContent>
        </Card>

        {/* Message Preview */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <MessageCircle className="size-5 text-success" />
                <CardTitle className="text-base">Mensaje WhatsApp</CardTitle>
              </div>
              <Badge variant="outline" className="text-xs">
                <Bot className="mr-1 size-3" />
                Redactado por IA
              </Badge>
            </div>
            <CardDescription>
              Mensaje automatico para {contacts[selectedContact].name}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* Contact Info */}
              <div className="flex items-center justify-between rounded-lg bg-muted/50 p-3">
                <div className="flex items-center gap-3">
                  <div className="flex size-10 items-center justify-center rounded-full bg-success/10">
                    <MessageCircle className="size-4 text-success" />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-foreground">{contacts[selectedContact].name}</p>
                    <p className="text-xs text-muted-foreground">{contacts[selectedContact].phone}</p>
                  </div>
                </div>
                <Badge
                  variant="outline"
                  className={
                    contacts[selectedContact].urgency === "critical"
                      ? "bg-destructive/10 text-destructive border-destructive/20"
                      : "bg-warning/10 text-warning-foreground border-warning/20"
                  }
                >
                  {contacts[selectedContact].urgency === "critical" ? (
                    <>
                      <AlertCircle className="mr-1 size-3" />
                      Urgente
                    </>
                  ) : (
                    <>
                      <Clock className="mr-1 size-3" />
                      Pendiente
                    </>
                  )}
                </Badge>
              </div>

              {/* Message Bubble */}
              <div className="rounded-lg bg-success/5 border border-success/10 p-4">
                <div className="flex items-center gap-1 mb-2 text-xs text-muted-foreground">
                  <Sparkles className="size-3 text-primary" />
                  Mensaje generado por IA
                </div>
                <p className="text-sm leading-relaxed text-foreground">
                  {generateMessage(contacts[selectedContact])}
                </p>
              </div>

              {/* Documents Needed */}
              <div>
                <h4 className="text-xs font-medium text-muted-foreground mb-2">Documentos solicitados:</h4>
                <div className="flex flex-wrap gap-2">
                  {contacts[selectedContact].missing.map((doc) => (
                    <Badge key={doc} variant="destructive" className="text-xs">
                      <AlertCircle className="mr-1 size-3" />
                      {doc}
                    </Badge>
                  ))}
                </div>
              </div>

              <Separator />

              {/* Action Buttons */}
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">
                  {sentMessages.has(selectedContact)
                    ? "Mensaje enviado exitosamente"
                    : "Listo para enviar por WhatsApp"}
                </span>
                <Button
                  onClick={() => handleSend(selectedContact)}
                  disabled={sentMessages.has(selectedContact)}
                  className={sentMessages.has(selectedContact) ? "bg-success text-success-foreground" : ""}
                >
                  {sentMessages.has(selectedContact) ? (
                    <>
                      <CheckCircle2 className="mr-2 size-4" />
                      Enviado
                    </>
                  ) : (
                    <>
                      <Send className="mr-2 size-4" />
                      Enviar Recordatorio IA
                    </>
                  )}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// angular/src/app/features/notificaciones/notificaciones.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NotificacionesService } from '../../core/services';
import type { Contact } from '../../shared/models';

@Component({
  selector: 'app-notificaciones',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './notificaciones.component.html',
})
export class NotificacionesComponent implements OnInit {
  contacts: Contact[] = [];
  selectedIndex = 0;
  sentMessages = new Set<number>();
  loading = true;

  constructor(private notificacionesService: NotificacionesService) {}

  ngOnInit(): void {
    this.notificacionesService.getContactosPendientes().subscribe({
      next: (list) => {
        this.contacts = list;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      },
    });
  }

  get selected(): Contact | null {
    return this.contacts[this.selectedIndex] ?? null;
  }

  message(contact: Contact): string {
    const docList = contact.missing.join(' y ');
    const firstName = contact.name.split(' ')[0];
    return `Hola ${firstName}, para no perder su subsidio de vivienda, necesitamos que nos envíe una foto de su ${docList} vigente lo antes posible. Puede responder a este mensaje con la foto o acercarse a nuestra oficina. Cualquier duda estamos para ayudarle.`;
  }

  enviar(contact: Contact): void {
    const id = contact.id;
    if (id == null) return;
    this.notificacionesService.marcarEnviado(id).subscribe({
      next: () => {
        this.sentMessages = new Set(this.sentMessages).add(id);
      },
    });
  }
}

<div class="d-flex flex-column gap-4">
  @if (loading) {
    <div class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
      <p class="small text-body-secondary mt-2 mb-0">Cargando contactos...</p>
    </div>
  } @else {
  <div class="row g-4">
    <div class="col-12 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h6 class="mb-0">Contactos Pendientes</h6>
          <small class="text-body-secondary">Beneficiarios con documentos faltantes</small>
        </div>
        <div class="card-body p-2">
          @for (c of contacts; track c.id ?? c.rut; let i = $index) {
            <button type="button" class="btn btn-light w-100 text-start d-flex align-items-start gap-2 p-3 mb-2 rounded border" [class.border-primary]="selectedIndex === i" [class.bg-primary]="selectedIndex === i" [class.bg-opacity-10]="selectedIndex === i" (click)="selectedIndex = i">
              <div class="position-relative">
                <span class="rounded-circle bg-secondary bg-opacity-25 d-inline-flex align-items-center justify-content-center" style="width: 40px; height: 40px;"><i class="bi bi-person text-body-secondary"></i></span>
                <span class="position-absolute top-0 start-100 translate-middle rounded-circle border border-2 border-white" [class.bg-danger]="c.urgency === 'critical'" [class.bg-warning]="c.urgency === 'warning'" style="width: 12px; height: 12px;"></span>
              </div>
              <div class="flex-grow-1 min-w-0">
                <div class="fw-medium text-truncate">{{ c.name }}</div>
                <div class="small text-body-secondary">{{ c.committee }}</div>
                <div class="d-flex flex-wrap gap-1 mt-1">
                  @for (doc of c.missing; track doc) {
                    <span class="badge bg-danger bg-opacity-10 text-danger small">{{ doc }}</span>
                  }
                </div>
                <div class="small text-body-secondary mt-1"><i class="bi bi-clock me-1"></i>{{ c.lastContact }}</div>
              </div>
              @if (c.id != null && sentMessages.has(c.id)) {
                <i class="bi bi-check-circle-fill text-success"></i>
              }
            </button>
          }
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-8">
      @if (selected) {
        <div class="card">
          <div class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2">
            <div>
              <span class="fw-medium">{{ selected.name }}</span>
              <span class="badge ms-2" [class.bg-danger]="selected.urgency === 'critical'" [class.bg-warning]="selected.urgency === 'warning'">
                {{ selected.urgency === 'critical' ? 'Urgente' : 'Pendiente' }}
              </span>
              <div class="small text-body-secondary mt-1"><i class="bi bi-telephone me-1"></i>{{ selected.phone }}</div>
            </div>
          </div>
          <div class="card-body">
            <div class="rounded p-3 bg-success bg-opacity-10 border border-success border-opacity-25 mb-3">
              <div class="small text-body-secondary mb-2"><i class="bi bi-stars text-primary me-1"></i> Mensaje generado por IA</div>
              <p class="small mb-0">{{ message(selected) }}</p>
            </div>
            <div class="mb-3">
              <h6 class="small text-body-secondary mb-2">Documentos solicitados:</h6>
              <div class="d-flex flex-wrap gap-2">
                @for (doc of selected.missing; track doc) {
                  <span class="badge bg-danger"><i class="bi bi-exclamation-circle me-1"></i>{{ doc }}</span>
                }
              </div>
            </div>
            <hr>
            <div class="d-flex justify-content-between align-items-center">
              <span class="small text-body-secondary">Enviar por WhatsApp / SMS</span>
              <button class="btn btn-primary btn-sm" (click)="selected && enviar(selected)" [disabled]="selected && selected.id != null && sentMessages.has(selected.id)">
                <i class="bi bi-send me-1"></i> Enviar
              </button>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
  }
</div>
